<!DOCTYPE html>
<html lang="{{lang.code}}">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="format-detection" content="telephone=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>{{title}}</title>
    <base href="{{basePath}}"/>

    <link href="{{basePath}}assets/css/panzehir.css" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{{basePath}}assets/img/favicon.ico" type="image/x-icon"> 
 
</head>

<body>

{%block headContent%} {%endblock%}
{%block pageContent%} {%endblock%}
 
{%block footScript%} {%endblock%}  
</body>
</html>
